version: 2
references:
  cache_key: &cache_key
    key: cache-{{ checksum "Dockerfile" }}
  workspace: &workspace ~/workspace
  attach_debug_workspace: &attach_debug_workspace
    attach_workspace:
      at: *workspace
  persist_debug_workspace: &persist_debug_workspace
    persist_to_workspace:
      root: *workspace
      paths:
        - .
  java_config: &java_config
    working_directory: *workspace
    docker:
      - image: circleci/openjdk:8u162-jdk-node-browsers
    environment:
      TERM: dumb
      JVM_OPTS: "-Xmx3200m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx3200m"'
jobs:
  deploy_image:
    <<: *java_config
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker build
          command: docker build -t "$DOCKER_USER/jenkins-android-docker-slave:latest" .
      - run:
          name: Docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Docker push
          command: docker push "$DOCKER_USER/jenkins-android-docker-slave:latest"
workflows:
  version: 2
  workflow:
    jobs:
      - deploy_image:
          context: my-docker
          filters:
            branches:
              only:
                - master
